baseURL = "/"
title = "数の舍"
theme = "hugo-theme-m10c"
paginate = 5

[menu]
  [[menu.main]]
    identifier = "back"
    name = "back"
    url = "/"
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "http://shiny.baoliu.ink/home/"
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"

[params]
  author = "Roy"
  description = "Welcome! :)"
  description_2 = "Tel/Wechat: 13051897793"
  description_3 = "Email: roycufe@gmail.com"
  description_4 = " "
  menu_item_separator = " - "
  favicon = "shutu.ico"
  [[params.social]]
    name = "github"
    url = "https://github.com/liubao210"
  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/roycufe"
  [[params.social]]
    name = "site"
    url = "http://baoliu.ink"
  # Brown theme
  #[params.style]
  #  darkestColor = "#463625"
  #  darkColor = "#2a3738"
  #  primaryColor = "#eeee6a"
  #  lightColor = "#96a879"
  #  lightestColor = "#ffffff"

  # Green theme
  #[params.style]
  #  darkestColor = "#315659"
  #  darkColor = "#253031"
  #  primaryColor = "#dad865"
  #  lightColor = "#96a879"
  #  lightestColor = "#fff"

  # Red and black theme
  #[params.style]
  #  darkestColor = "#d35050"
  #  darkColor = "#212121"
  #  primaryColor = "#ffffff"
  #  lightColor = "#a2a2a2"
  #  lightestColor = "#d3d3d3"
